name: Health check

on:
  schedule:
    - cron: 0 0/6 * * *
  repository_dispatch:
    types: [health_check]

permissions: {}

concurrency:
  group: health-check
  cancel-in-progress: true

jobs:
  health_check:
    name: Health check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
      - run: deno task health_check
