name: publish

on:
  release:
    types: [published]

permissions: {}

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout the repository
      id-token: write # to authenticate with JSR
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
      - name: Set version from release tag
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s/\"version\": \"0.0.0\"/\"version\": \"${RELEASE_TAG}\"/" deno.jsonc
      - run: deno task ci
      - run: deno publish --allow-dirty
